spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/security
    username: bootuser
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  thymeleaf:
    cache: false

  profiles:
    include: oauth

logging:
  level:
    HCY: debug
    org:
      springframework:
        security:
          web: trace

